// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdiqfcrmxkzoglwzdink.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkaXFmY3JteGt6b2dsd3pkaW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjU5MzgsImV4cCI6MjA3NDA0MTkzOH0.PYSnmHVPUs1J_qOmWHwS2dwLpUrz6_AX71BxG2WbQCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});